[workspace]
default-members = ["game"]
members = [
    "engine",
    "game",
    "engine/math",
    "utils",
    "graphics",
    "engine/platforms/winit",
    "engine/assets",
    "asset_library",
    "scripting",
    "mesh",
    "tools/gltf_extract_meshes",
]
