[workspace]
default-members = ["game", "tools/zr_convert_gltf"]
members = [
    "engine",
    "game",
    "engine/math",
    "utils",
    "engine/graphics",
    "engine/platforms/winit",
    "engine/assets",
    "scripting",
    "mesh",
    "tools/zr_convert_gltf"
]
