vk_api_major_version = 1
vk_api_minor_version = 0
vk_api_patch_version = 0
instance_validation_layer_names = [
"VK_LAYER_KHRONOS_validation"
]
instance_extension_names = []
#preferred_device = "Intel(R) UHD Graphics 630"
prefer_integrated_gpu = false
prevent_tearing = true
limit_frame_rate = true
preferred_frames_in_flight = 2
resize_on_sub_optimal = true
use_transfer_queues = true
enable_debug_utils = true