[package]
name = "zircon_platform_winit"
version = "0.1.0"
edition = "2021"

[lib]
name = "platform_winit"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zircon_engine = { path = "../.." }
graphics = { path = "../../../graphics" }
utils = { path = "../../../utils" }
winit = "0.27.2"
